name = "IntegrationInterface"
uuid = "03ca86a4-b7cd-4b10-a38f-d7a84f40de1e"
authors = ["Pablo San-Jose <lekand@gmail.com> and contributors"]
version = "0.1.1"

[deps]

[weakdeps]
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
HAdaptiveIntegration = "eaa5ad34-b243-48e9-b09c-54bc0655cecf"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extensions]
IntegrationInterfaceCubatureExt = "Cubature"
IntegrationInterfaceHAdaptiveIntegrationExt = "HAdaptiveIntegration"
IntegrationInterfaceHCubatureExt = "HCubature"
IntegrationInterfaceLinearAlgebraExt = "LinearAlgebra"
IntegrationInterfaceQuadGKExt = "QuadGK"
IntegrationInterfaceSparseArraysExt = "SparseArrays"

[compat]
HAdaptiveIntegration = "1.1"
Cubature = "1.5.1"
HCubature = "1.8.0"
QuadGK = "2.11.2"
julia = "1.10"

[extras]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "QuadGK", "HCubature", "Cubature", "HAdaptiveIntegration", "FastGaussQuadrature", "Unitful"]
